set-option -g prefix 'C-\' 
# set-window-option -g mode-keys vi
# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# livereload... :)
bind R source-file ~/.tmux.conf \; display-message "tmux configuration has been reloaded"

set-option -g status-bg blue

# mouse can be used to select panes
set-option -g mouse-select-pane on

# mouse can be used to select windows (by clicking in the status bar)
set-option -g mouse-select-window on

# mouse can be used to resize panes (by dragging dividers)
set-option -g mouse-resize-pane on

# not really sure what this does, but with it, the scrollwheel works inside Vim
# set-option -g mouse-utf8 on

# allow mouse to enter copy mode and initiate selection
set-window-option -g mode-mouse on

# I originally had this as screen-256color, but this works
# out-of-the-box in more places
set -g default-terminal "screen"
